#use_frameworks!
source 'https://github.com/DecembeGrirl/sy-spec-repo.git'

platform :ios, '9.0'

target 'testA_Example' do
  pod 'testA', :path => '../'

  target 'testA_Tests' do
    inherit! :search_paths

    
  end
end
